# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish To GH Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/Los_Angeles
    - name: firebaseConfig
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: cd website; echo "${FIREBASE_CONFIG}" > src/firebaseConfig.json;  cd ..
    - run: git submodule init ;  git submodule update 
    - run: pushd ./COVID-19/ ; git checkout master; git pull; popd
    - run: pushd  ./coronavirus-data/ ;  git checkout master; git pull; popd
    - run: pushd  ./vaccine-module/ ;  git checkout master; git pull; popd
    - run: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi
    - run: cd website; npm ci  ; cd ..
    - run: cd website; npm run data; cd ..
    - run: cd website; npm run build --if-present; cd ..
    - run: cd website; echo "covid-19.town" > build/CNAME; cd ..
    - name: Setup new git
      run: cd website; git init; git remote add origin git@github.com:xunhuang/my-app.git; cd ..
    - name: Deploy
      run: cd website node node_modules/gh-pages/bin/gh-pages.js -d build

